In [1]:
!pip install pandas
!pip install openpyx1
!pip install plotly
!pip install nbformat

Requirement already satisfied: pandas in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\PC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement openpyx1 (from versions: none)
ERROR: No matching distribution found for openpyx1

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\PC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting plotly
  Downloading plotly-6.6.0-py3-none-any.whl.metadata (8.5 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.18.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly) (26.0)
Downloading plotly-6.6.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB 9.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.9 MB 17.1 MB/s eta 0:00:01
   ---------- ----------------------------- 2.5/9.9 MB 19.8 MB/s eta 0:00:01
   -------------- ------------------------- 3.5/9.9 MB 20.5 MB/s eta 0:00:01
   ------------------- -------------------- 4.9/9.9 MB 20.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.1/9.9 MB 20.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/9.9 MB 20.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/9.9 MB 20.6 MB/s eta 0:00:01
   ------------------------------------ --- 9.1/9.9 MB 20.8 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 21.1 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 21.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 17.6 MB/s eta 0:00:00
Downloading narwhals-2.18.0-py3-none-any.whl (444 kB)
   ---------------------------------------- 0.0/444.9 kB ? eta -:--:--
   --------------------------------------  440.3/444.9 kB 26.9 MB/s eta 0:00:01
   ---------------------------------------- 444.9/444.9 kB 9.2 MB/s eta 0:00:00
Installing collected packages: narwhals, plotly
Successfully installed narwhals-2.18.0 plotly-6.6.0

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\PC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema>=2.6 (from nbformat)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nbformat) (5.14.3)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat)
  Downloading rpds_py-0.30.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.5 kB ? eta -:--:--
   ---------------------------------------- 78.5/78.5 kB 2.2 MB/s eta 0:00:00
Downloading fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
   ---------------------------------------- 0.0/90.6 kB ? eta -:--:--
   ------------------------------------ --- 81.9/90.6 kB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 90.6/90.6 kB 1.7 MB/s eta 0:00:00
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
   ---------------------------------------- 0.0/67.6 kB ? eta -:--:--
   ---------------------------------------- 67.6/67.6 kB 1.9 MB/s eta 0:00:00
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.30.0-cp311-cp311-win_amd64.whl (236 kB)
   ---------------------------------------- 0.0/236.0 kB ? eta -:--:--
   ---------------------------------------- 236.0/236.0 kB 7.1 MB/s eta 0:00:00
Installing collected packages: fastjsonschema, rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, nbformat
Successfully installed attrs-25.4.0 fastjsonschema-2.21.2 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.37.0 rpds-py-0.30.0

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\PC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# Carga datos

In [8]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------  245.8/250.9 kB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 3.1 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\PC\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd

data=pd.read_excel ("ventas.xlsx")

In [17]:

data.head()

,Costo,Clave Cliente,Descuento,Ubicación Clave,Fecha De Orden,Clave Producto,Utilidad,Cantidad,Clave Vendedor,Ventas,Fecha Envío
0,0.55,NK-18490,0.0,530,2017-10-12,1683,0.4356,1,5,0.990,2017-10-14
1,0.66,TM-21010,0.0,27,2015-09-12,982,0.5828,1,10,1.240,2015-09-18
2,0.84,DM-12955,0.2,246,2016-03-21,1167,0.5040,1,7,1.344,2016-03-25
3,0.84,TB-21055,0.0,587,2016-06-17,1167,0.8400,1,10,1.680,2016-06-18
4,0.90,LS-16975,0.0,34,2017-11-28,396,0.7380,1,10,1.640,2017-12-04

In [18]:
data.tail

<bound method NDFrame.tail of          Costo Clave Cliente  Descuento  Ubicación Clave Fecha De Orden  \
0         0.55      NK-18490        0.0              530     2017-10-12
1         0.66      TM-21010        0.0               27     2015-09-12
2         0.84      DM-12955        0.2              246     2016-03-21
3         0.84      TB-21055        0.0              587     2016-06-17
4         0.90      LS-16975        0.0               34     2017-11-28
...        ...           ...        ...              ...            ...
9072   7279.98      RB-19360        0.0              546     2017-03-23
9073   7279.98      TA-21385        0.2              400     2017-10-22
9074   9099.97      TC-20980        0.0              281     2016-10-02
9075  11099.96      CS-12505        0.7              292     2016-11-25
9076  11839.97      GT-14635        0.5               70     2017-11-04

      Clave Producto   Utilidad  Cantidad  Clave Vendedor     Ventas  \
0               1683     0.4356         1               5      0.990
1                982     0.5828         1              10      1.240
2               1167     0.5040         1               7      1.344
3               1167     0.8400         1              10      1.680
4                396     0.7380         1              10      1.640
...              ...        ...       ...             ...        ...
9072            1650  6719.9808         4              10  13999.960
9073            1650  3919.9888         4              12  11199.968
9074            1650  8399.9760         5               9  17499.950
9075            1888 -6599.9780         5              10   4499.985
9076            1737 -3839.9904         4               7   7999.980

     Fecha Envío
0     2017-10-14
1     2015-09-18
2     2016-03-25
3     2016-06-18
4     2017-12-04
...          ...
9072  2017-03-25
9073  2017-10-24
9074  2016-10-09
9075  2016-12-02
9076  2017-11-04

[9077 rows x 11 columns]>

In [19]:
data.Costo

0           0.55
1           0.66
2           0.84
3           0.84
4           0.90
          ...
9072     7279.98
9073     7279.98
9074     9099.97
9075    11099.96
9076    11839.97
Name: Costo, Length: 9077, dtype: float64

In [20]:
data.Utilidad

0          0.4356
1          0.5828
2          0.5040
3          0.8400
4          0.7380
          ...
9072    6719.9808
9073    3919.9888
9074    8399.9760
9075   -6599.9780
9076   -3839.9904
Name: Utilidad, Length: 9077, dtype: float64

In [23]:
data[["Clave Cliente","Utilidad","Costo"]]

     Clave Cliente   Utilidad     Costo
0         NK-18490     0.4356      0.55
1         TM-21010     0.5828      0.66
2         DM-12955     0.5040      0.84
3         TB-21055     0.8400      0.84
4         LS-16975     0.7380      0.90
...            ...        ...       ...
9072      RB-19360  6719.9808   7279.98
9073      TA-21385  3919.9888   7279.98
9074      TC-20980  8399.9760   9099.97
9075      CS-12505 -6599.9780  11099.96
9076      GT-14635 -3839.9904  11839.97

[9077 rows x 3 columns]

In [24]:
data.describe()

,Costo,Descuento,Ubicación Clave,Fecha De Orden,Clave Producto,Utilidad,Cantidad,Clave Vendedor,Ventas,Fecha Envío
count,9077.000000,9077.000000,9077.000000,9077,9077.000000,9077.000000,9077.000000,9077.000000,9077.000000,9077
mean,176.459016,0.148175,336.091220,2016-10-02 19:27:36.626638,936.321362,27.547348,3.806324,9.056406,204.006266,2016-10-06 18:22:53.052770
min,0.550000,0.000000,1.000000,2015-01-02 00:00:00,1.000000,-6599.978000,1.000000,1.000000,0.444000,2015-01-04 00:00:00
25%,11.500000,0.000000,197.000000,2015-12-19 00:00:00,494.000000,2.173600,2.000000,10.000000,16.096000,2015-12-24 00:00:00
50%,33.500000,0.100000,356.000000,2016-11-04 00:00:00,970.000000,8.643600,3.000000,10.000000,45.980000,2016-11-08 00:00:00
75%,145.530000,0.200000,469.000000,2017-07-20 00:00:00,1350.000000,27.316800,5.000000,10.000000,173.940000,2017-07-24 00:00:00
max,11839.970000,0.800000,632.000000,2017-12-30 00:00:00,1894.000000,8399.976000,14.000000,14.000000,17499.950000,2018-01-05 00:00:00
std,464.804384,0.200270,168.148059,NaN,519.295669,227.602530,2.251133,2.798648,554.103362,NaN

In [25]:
data["Clave Cliente"].unique()

<StringArray>
['NK-18490', 'TM-21010', 'DM-12955', 'TB-21055', 'LS-16975', 'NS-18505',
 'RM-19375', 'MA-17560', 'DC-12850', 'BM-11140',
 ...
 'JH-16180', 'AO-10810', 'GM-14680', 'AB-10015', 'EJ-13720', 'PK-18910',
 'SH-20635', 'SC-20020', 'JR-15700', 'MW-18235']
Length: 790, dtype: str

In [26]:
data.head()

,Costo,Clave Cliente,Descuento,Ubicación Clave,Fecha De Orden,Clave Producto,Utilidad,Cantidad,Clave Vendedor,Ventas,Fecha Envío
0,0.55,NK-18490,0.0,530,2017-10-12,1683,0.4356,1,5,0.990,2017-10-14
1,0.66,TM-21010,0.0,27,2015-09-12,982,0.5828,1,10,1.240,2015-09-18
2,0.84,DM-12955,0.2,246,2016-03-21,1167,0.5040,1,7,1.344,2016-03-25
3,0.84,TB-21055,0.0,587,2016-06-17,1167,0.8400,1,10,1.680,2016-06-18
4,0.90,LS-16975,0.0,34,2017-11-28,396,0.7380,1,10,1.640,2017-12-04

In [27]:
data["Clave Vendedor"].value_counts()

Clave Vendedor
10    5837
12     281
11     280
1      279
2      254
13     253
9      247
8      247
5      239
14     238
4      237
6      234
3      232
7      219
Name: count, dtype: int64